"""empty message

Revision ID: 221bd092be5f
Revises: f3b964a91de7
Create Date: 2026-03-27 20:41:27.242632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221bd092be5f'
down_revision = 'f3b964a91de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
